### PR TITLE
Godot 4.0 Update

### PR DESCRIPTION
**Pull request by allenwp**
Hey there, thanks for the great mirror asset! This pull request updates the project to Godot 4.0. There is an outstanding issue that affects Godot 3.5 regarding the way the addon plugin is configured that I haven't fixed with this pull request.

### CODE REVIEW

**Comment by Norodix** [comment]
Hey!
Thanks for the PR! I will go through it and test it when I have some time.
I guess the weekend maybe :)

**Comment by allenwp** [comment]
Great, thanks! There is also the following error that happens when instantiating a scene with a SubViewport and material that uses the texture from that SubViewport:
```
Mirror.gd:21 @ _enter_tree(): Condition "proxy.is_valid()" is true.
  <C++ Source>   scene/main/viewport.cpp:89 @ setup_local_to_scene()
  <Stack Trace>  Mirror.gd:21 @ _enter_tree()
```

There seems to be a lot of development work surrounding SubViewports in Godot 4.0, so I think this issue will be fixed in an upcoming 4.0 RC. I think the specific fix to this error can be found as a pull request to [this issue.](https://github.com/godotengine/godot/issues/60350) Because of this, I've just been ignoring this error for now.

**Comment by Norodix** [comment]
Hey!

Sorry for not getting back sooner. I started learning about the differences of the new engine and I'll soon get around to test and merge this PR.

Do you happen to know any recommendation on how to add different versions of the same plugin to the new asset lib? I see a lot of plugins creating a separate v4 branch but I don't know if that is for development or that is a real convention.

Thanks!

**Comment by allenwp** [comment]
Hey, no worries. Full disclosure: this was my first time ever working with Godot and I have no other experience with plugins. My goal was just to get this plugin to be behaving the same on Godot 4.0 as it does using Godot 3.5, if you ignore the `"proxy.is_valid()" is true` issue that seems to be a known issue, as I mentioned.

So to answer your question: I have no idea, sorry!

**Comment by allenwp** [comment]
Hey, no worries. Full disclosure: this was my first time ever working with Godot and I have no other experience with plugins. My goal was just to get this plugin to be behaving the same on Godot 4.0 as it does using Godot 3.5, if you ignore the `"proxy.is_valid()" is true` issue that seems to be a known issue, as I mentioned.

So to answer your question: I have no idea, sorry!

**Comment by Norodix** [comment]
Applied some small fixes and pushed it to a new branch.
You can find it under https://github.com/Norodix/GodotMirror/tree/godot4

Thanks for the help! : )

**Comment by allenwp** [comment]
Nice!

**Pull request closed without merging**
