### PR TITLE
Linear filtering + Shader dusting

### PR DESCRIPTION
**Pull request by Firepal**
MirrorMaterial:
- no longer a binary file
- ViewportTexture now looks smooth and not blocky. Linear filtering is *cheap*

MirrorShader:
- MeshInstancedFlipped removed, superseded by siÃmple shader math
- Linear2srgb separated and disabled, replaced with the (cheaper?) Keep 3D Linear in Viewport

### CODE REVIEW

**Comment by Firepal** [comment]
forgot to version bump in `plugin.cfg`, welp

**Review by Norodix — APPROVED** [review]
Very good changes, I really like it. 

One thing missing is a default distortion texture. I set it up because its easier to showcase this small feature if by default the user only needs to drag a slider back and forth. 

The best would be to export the distortion texture to the top level script to let the user pick one as they see fit. Do you know how that could be done?

**Comment by Firepal** [comment]
> Very good changes, I really like it.

Np. I will try and do more when I'm off holiday :)

> One thing missing is a default distortion texture.

> The best would be to export the distortion texture to the top level script to let the user pick one as they see fit. Do you know how that could be done?

Easy. We can make an exported Texture variable, and add a setter function to it that sets the given texture (or if null, the default stored as a `.tres`) on the shader using `ShaderMaterial.set_shader_param(name,value)`.

Instead of only fixing the missing texture, we could implement that and solve two in one!

**Comment by Norodix** [comment]
Damn it. I even searched for it but now that you mention I immediately find this type of export variable.

**Pull request merged**
